services:
  - type: web
    name: kalisalakrt02
    runtime: node
    region: singapore
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3005
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        sync: false
      - key: TELEGRAM_WEBHOOK_SECRET
        sync: false